Feature/59952 file attachments output
Cognigy/chat-components pull request #30
Opened 2024-01-26 15:41 UTC by sushmi21

Thus PR adds the chat components needed to display the file attachment outputs

NOTE: Please also review the PR is socket client repo before this https://github.com/Cognigy/SocketClient/pull/33

- Please check if the UI is same as the Figma prototypes
- If a file has a long name, then it will be replaced with ellipsis
- You should be able to click the file and open it in new browser tab
- To test: The file attchment output sample is added to UI components tab

2024-01-29 13:30 UTC, dshire requested changes
1. When I get a message with text and attachments, I only see the text message, the attachment previews are missing (saw the same behavior already before these changes but needs fixing)
2. The image attachments don't have a preview anymore, this looks like a regression compared to the old one ( see below)

![Screenshot from 2024-01-24 10-57-35](https://github.com/Cognigy/chat-components/assets/30043753/d66be4ee-1753-406c-9924-3abb87a58d36)

2024-01-29 13:46 UTC, sushmi21 commented
> 1. When I get a message with text and attachments, I only see the text message, the attachment previews are missing (saw the same behavior already before these changes but needs fixing)
> 
> ![Screenshot from 2024-01-29 14-28-26](https://private-user-images.githubusercontent.com/30043753/300477197-e01605ea-4975-416d-835d-4f24a2ad15ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzU4NTUsIm5iZiI6MTcwNjUzNTU1NSwicGF0aCI6Ii8zMDA0Mzc1My8zMDA0NzcxOTctZTAxNjA1ZWEtNDk3NS00MTZkLTgzNWQtNGYyNGEyYWQxNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEzMzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDI5Yzc3MzYyNDQxYTE3NWVkZjk5NmQ0OWUyY2UwY2ZhMTU5NTAyOTc0YzcwNTIxYTgwNWQ1ODE4ODBjOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7cgQgpzMxdU3V78rQqglTHeij9EpNWRb9i8IQ8P5NI)
> 
> 2. The image attachments don't have a preview anymore, this looks like a regression compared to the old one ( see below)
> 
> ![Screenshot from 2024-01-24 10-57-35](https://private-user-images.githubusercontent.com/30043753/300476545-d66be4ee-1753-406c-9924-3abb87a58d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzU4NTUsIm5iZiI6MTcwNjUzNTU1NSwicGF0aCI6Ii8zMDA0Mzc1My8zMDA0NzY1NDUtZDY2YmU0ZWUtMTc1My00MDZjLTk5MjQtM2FiYjg3YTU4ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDEzMzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZjEwMWFmM2ZiZmJiZTVjOWQ3YzBjY2Q0YjFmOTgwOGY3NmFkYzdkYTI0NGRiNTc2NzE3ODZkN2JmOWZiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rrew6BhaPbAYaBmHwv8rCdslw3fBQ9bnK1zl8av46gM)

1. I will check if the issue should be fixed here or in the WebchatWidget repo.
2. This is how the Figma designs are. This is the same with the file attachment inputs. We now don't show the preview in file inputs too. IMO it is fine, since we can still open the attachments in the browser anyway.

![Screenshot from 2024-01-29 14-43-01](https://github.com/Cognigy/chat-components/assets/29442479/202b6788-cd93-4531-9663-166385353842)

2024-01-29 17:27 UTC, sushmi21 commented
> 1. When I get a message with text and attachments, I only see the text message, the attachment previews are missing (saw the same behavior already before these changes but needs fixing)
> 
> ![Screenshot from 2024-01-29 14-28-26](https://private-user-images.githubusercontent.com/30043753/300477197-e01605ea-4975-416d-835d-4f24a2ad15ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDk0NTMsIm5iZiI6MTcwNjU0OTE1MywicGF0aCI6Ii8zMDA0Mzc1My8zMDA0NzcxOTctZTAxNjA1ZWEtNDk3NS00MTZkLTgzNWQtNGYyNGEyYWQxNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE3MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMDJlOTQ0YWQwZTQzNGY0NzJiZWZiMTNiM2MxOWIyODQ5NDFlNjVhZjI0NDFmZGMzNWQ0ZDcxM2NhMTBhNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w_rpSIYuVmZwtLuGruHUah8Gks3x8C0YcBPrHiewrm0)
> 
> 2. The image attachments don't have a preview anymore, this looks like a regression compared to the old one ( see below)
> 
> ![Screenshot from 2024-01-24 10-57-35](https://private-user-images.githubusercontent.com/30043753/300476545-d66be4ee-1753-406c-9924-3abb87a58d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDk0NTMsIm5iZiI6MTcwNjU0OTE1MywicGF0aCI6Ii8zMDA0Mzc1My8zMDA0NzY1NDUtZDY2YmU0ZWUtMTc1My00MDZjLTk5MjQtM2FiYjg3YTU4ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE3MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWNkZWFjOTZmZDVmM2ZiZDk3YTM3MzkxY2YxYTY1NzhiOGYxMjg4Yzg3MWVkZDlmZGI4NDE2YmVlYTRiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xW4-exWKdT5h9cQf_lJ4n_Y6g55orSRgkwZW8ekTs5A)

UPDATE: I have fixed the 'message with text and attachments' situation in this PR. PR is ready for a re-review

2024-01-30 08:41 UTC, dshire requested changes
Please also do a "npm version minor" and commit and push

2024-01-30 09:23 UTC, dshire approved these changes

2024-01-30 09:23 UTC, merged